dbt_github:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: dj89792.ap-south-1.aws.snowflakecomputing.com
      database: DBT_SLACK
      warehouse: SLACK
      schema: dev
      role: ACCOUNTADMIN
      threads: 1
      user: skush
      password: Mynameishs12345@
  