dbt_github:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: dj89792.ap-south-1
      database: dbt_slack
      warehouse: SLACK
      schema: dev
      role: SYSADMIN
      threads: 1
      user: skush
      password: Mynameishs12345@
  