dbt_github:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: https://dj89792.ap-south-1.aws.snowflakecomputing.com
      database: ANALYTICS
      warehouse: COMPUTE_WH
      schema: PUBLIC
      role: ACCOUNTADMIN
      threads: 1
      user: skush
      password: Mynameishs12345@
  