dbt_github:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: qh16214.ap-southeast-1
      database: dbt_github
      warehouse: DBT
      schema: dev
      role: SYSADMIN
      threads: 1
      user: "{{env_var('gitu')}}"
      password: "{{env_var('gitp')}}"
  