dbt_github:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: dj89792.ap-south-1
      database: RAW
      warehouse: COMPUTE_WH
      schema: PUBLIC
      role: ACCOUNTADMIN
      threads: 1
      user: skush
      password: Mynameishs12345@
  