dbtgitlab:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: qh16214.ap-southeast-1
      database: dbt_github
      warehouse: DBT
      schema: dev
      role: SYSADMIN
      threads: 1
      user: cicd_skush  # jinja to access env var, can use diect also in '.gitlab-cicd.yml' file
      password: Admin@1234
  