name: dbt Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: xemuliam/dbt

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: Set up dbt
      #   run: |
      #     dbt --version

      # - name: Seed data
      #   run: dbt seed

      # - name: Run dbt tests
      #   run: dbt test

      # - name: Generate dbt documentation
      #   run: dbt docs generate

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Configure Git
        run: |
          git config --global user.email "animkush@gmail.com"
          git config --global user.name "Anim0011"

      - name: Check path
        run: |
          pwd

      # - name: Push changes to GitHub
      #   run: |
      #     git remote set-url origin "https://Anim0011:Mynameishs123@github.com/Anim0011/dbt_github.git"
      #     git add .
      #     git commit -m "Add dbt target folder"
      #     git push
