name: dbt Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: xemuliam/dbt

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Push changes.
        run: |
          git config --global user.email "animkush@gmail.com"
          git config --global user.name "Anim0011"
          git clone https://github.com/Anim0011/dbt_github
          cd ./dbt_github
          dbt seed
          dbt docs generate
          git add .
          git commit -m "Add dbt target folder"
          git push
