name: dbt Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: xemuliam/dbt

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: Set up dbt
      #   run: |
      #     dbt --version

      # - name: Seed data
      #   run: dbt seed

      # - name: Run dbt tests
      #   run: dbt test

      # - name: Generate dbt documentation
      #   run: dbt docs generate

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Set Github
        run: |
          git config --global user.email "animkush@gmail.com"
          git config --global user.name "Anim0011"
          
      - name: Set Repo
        run: |
          git clone https://github.com/Anim0011/dbt_github
          cd ./dbt_github

      - name: Push changes.
        run: |
          git add .
          git commit -m "Add dbt target folder"
          git push
