name: dbt Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: xemuliam/dbt:1.5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Push changes.
        env: 
          git_pass: ${{ SECRETS.git_pass }} 
          gitp: ${{ SECRETS.gitp }}
          gitu: ${{ SECRETS.gitu }}

        run: |
            dbt --version
            dbt debug
