name: dbt Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: xemuliam/dbt:1.5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Push changes.
        env: 
          git_pass: ${{ SECRETS.git_pass }} 
          gitp: ${{ SECRETS.gitp }}
          gitu: ${{ SECRETS.gitu }}

        run: |
          apt-get -y update
          apt-get -y upgrade
          dbt debug
          dbt seed
          dbt docs generate
          git clone https://github.com/Anim0011/dbt_github.git
          cd ./dbt_github
          git config --global user.email "animkush@gmail.com"
          git config --global user.name "Anim0011"
          cp -u -r target docs #updated #recursive
          git add .
          git commit -m "[skip ci] Added pages"
          git push https://$git_pass@github.com/Anim0011/dbt_github.git
